### ISSUE TITLE
make a new release?

### ISSUE THREAD

**Issue by bastelfreak** [denisdefreyne/cri#116]
Hi!
would it be possible to cut a new release? I'm packaging cri for Arch Linux and I need https://github.com/denisdefreyne/cri/commit/04c8aae3d34d47977db041a59520c560bc59b827 for a Ruby 3.2 rebuild.

**Comment by denisdefreyne** [comment]
Done!

@bastelfreak 2.15.12 is the release you’re looking for.

**Comment by bastelfreak** [comment]
thanks a lot!
